name: Update GitHub Stats Daily

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch: # manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: America/Boise
