name: Update GitHub Stats Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community
          config_timezone: America/Boise
          filename: github-metrics.svg
